### ISSUE TITLE
以前老版本的升级了没有搜索和清空按钮

### ISSUE THREAD

**Issue by sumic** [myloveGy/yii2-ace-admin#24]
确定CSS和JS文件已经更新了。页面没有生成button元素

**Comment by myloveGy** [comment]
需要确定你现在使用 jinxing/yii2-admin版本是那个版本！1.2.6 以后 我把css 和 js 拆分到 bower 里面去了！ 你需要删除 web/asset 下面的文件， 保证你引入的是最新的css 和 js 文件

 

发件人: sumic <notifications@github.com>
答复: myloveGy/yii2-ace-admin <reply@reply.github.com>
日期: 2019年9月27日 星期五 下午6:00
收件人: myloveGy/yii2-ace-admin <yii2-ace-admin@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24)

 

确定CSS和JS文件已经更新了。页面没有生成button元素

**Comment by myloveGy** [comment]
后面的按钮是我在 jinxing/yii2-admin 1.2.6 版本上加载的！如果你使用的是 jinxing/yii2-admin 1.0 版本， 不要升级 到 1.2 版本，不是很兼容

**Comment by sumic** [comment]
> 后面的按钮是我在 jinxing/yii2-admin 1.2.6 版本上加载的！如果你使用的是 jinxing/yii2-admin 1.0 版本， 不要升级 到 1.2 版本，不是很兼容

我用的是最老的版本。现在要重构前端，所以想升级。已经替换了JS和CSS文件，现在的问题就是页面连元素都没有生成，就谈不上CSS了。

**Comment by myloveGy** [comment]
不是 js 替换那么简单的！包括js 都有不兼容的地方的，你现在应该是js 报错了吧！你要用最新的话，前后端都需要按照最新的版本的写法！主要是视图页面里面的 meTables 初始化 和 主控制器的 查询

**Comment by sumic** [comment]
折腾了半天弄好了，全部重新搞了一下。顺便问下页面底端那个" (从 10 条记录过滤)"这个开关在哪儿？

**Comment by myloveGy** [comment]
这个是 jquery.datatables.js 的配置, 你要看http://www.datatables.club/reference/option/

这个的配置选项了、我也不是很清楚

 

发件人: sumic <notifications@github.com>
答复: myloveGy/yii2-ace-admin <reply@reply.github.com>
日期: 2019年11月6日 星期三 下午3:59
收件人: myloveGy/yii2-ace-admin <yii2-ace-admin@noreply.github.com>
抄送: "jinxing.liu" <821901008@qq.com>, Comment <comment@noreply.github.com>
主题: Re: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24)

 

折腾了半天弄好了，全部重新搞了一下。顺便问下页面底端那个" (从 10 条记录过滤)"这个开关在哪儿？

**Comment by sumic** [comment]
> 这个是 jquery.datatables.js 的配置, 你要看http://www.datatables.club/reference/option/ 这个的配置选项了、我也不是很清楚 发件人: sumic <notifications@github.com> 答复: myloveGy/yii2-ace-admin <reply@reply.github.com> 日期: 2019年11月6日 星期三 下午3:59 收件人: myloveGy/yii2-ace-admin <yii2-ace-admin@noreply.github.com> 抄送: "jinxing.liu" <821901008@qq.com>, Comment <comment@noreply.github.com> 主题: Re: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24) 折腾了半天弄好了，全部重新搞了一下。顺便问下页面底端那个" (从 10 条记录过滤)"这个开关在哪儿？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

就是没搞懂，我下载的你的包没有显示，我放到我的程序里面就显示了，看了下也没找到这个配置菜单。。。

**Comment by myloveGy** [comment]
你加我QQ: 82190100 吧

 

发件人: sumic <notifications@github.com>
答复: myloveGy/yii2-ace-admin <reply@reply.github.com>
日期: 2019年11月6日 星期三 下午4:29
收件人: myloveGy/yii2-ace-admin <yii2-ace-admin@noreply.github.com>
抄送: "jinxing.liu" <821901008@qq.com>, Comment <comment@noreply.github.com>
主题: Re: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24)

 

这个是 jquery.datatables.js 的配置, 你要看http://www.datatables.club/reference/option/ 这个的配置选项了、我也不是很清楚 发件人: sumic notifications@github.com 答复: myloveGy/yii2-ace-admin reply@reply.github.com 日期: 2019年11月6日 星期三 下午3:59 收件人: myloveGy/yii2-ace-admin yii2-ace-admin@noreply.github.com 抄送: "jinxing.liu" 821901008@qq.com, Comment comment@noreply.github.com 主题: Re: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24) 折腾了半天弄好了，全部重新搞了一下。顺便问下页面底端那个" (从 10 条记录过滤)"这个开关在哪儿？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

就是没搞懂，我下载的你的包没有显示，我放到我的程序里面就显示了，看了下也没找到这个配置菜单。。。

**Comment by sumic** [comment]
加你了，没反映呢？

**Comment by myloveGy** [comment]
我给QQ 给错了！ 821901008

 

发件人: sumic <notifications@github.com>
答复: myloveGy/yii2-ace-admin <reply@reply.github.com>
日期: 2019年11月6日 星期三 下午5:19
收件人: myloveGy/yii2-ace-admin <yii2-ace-admin@noreply.github.com>
抄送: "jinxing.liu" <821901008@qq.com>, Comment <comment@noreply.github.com>
主题: Re: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24)

 

加你了，没反映呢？

**Comment by myloveGy** [comment]
我给QQ给错了！ 821901008 

 

 

发件人: sumic <notifications@github.com>
答复: myloveGy/yii2-ace-admin <reply@reply.github.com>
日期: 2019年11月6日 星期三 下午5:19
收件人: myloveGy/yii2-ace-admin <yii2-ace-admin@noreply.github.com>
抄送: "jinxing.liu" <821901008@qq.com>, Comment <comment@noreply.github.com>
主题: Re: [myloveGy/yii2-ace-admin] 以前老版本的升级了没有搜索和清空按钮 (#24)

 

加你了，没反映呢？
